spring:
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/orders/**
        
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/payments/**
        
  application:
    name: api-gateway

server:
  port: 9000          