spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers:
    - localhost:9092
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka